### ISSUE TITLE
BehaviorRelay의 역할

### ISSUE THREAD

**Issue by Sueaty** [fimuxd/RxSwift#15]
안녕하세요,
Relay 관련 공부하다 들렀다가 제가 아는 것과 조금 다른 사항이 있어 issue 남깁니다.

[RxSwift/Ch3 Homework](https://github.com/fimuxd/RxSwift/blob/master/Lectures/03_Subjects/Ch3.%20Homework.md#각각을-어느용도에서-사용할-수-있을까) 파일에서 BehaviorRelay 관련 된 것입니다.

작성 된 ```선언할 때 설정해두었던 버퍼사이즈만큼의 이벤트``` 는 ReplaySubject에 대한 설명인데
BehaviorSubject의 행동방식으로 작성되어 있습니다 :)

**Comment by fimuxd** [comment]
그렇네요! 수정하겠습니다. 감사합니다 :)
